services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jack
      POSTGRES_DB: securityDB
    ports:
      - "5050:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

  courseApi:
    build: .
    container_name: course-api-app
    ports:
      - "4040:7070"
    depends_on:
      - postgres
    environment:
        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        SECURITY_JWT_SECRET_KEY: ${SECURITY_JWT_SECRET_KEY}
        SECURITY_JWT_EXPIRATION_TIME: ${SECURITY_JWT_EXPIRATION_TIME}
volumes:
  postgres_data:
