server:
  port: 7070
spring:
  application:
    name: course-spring-security
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5050/securityDB}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:jack}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true